#!/usr/bin/env bash
# fix-cloudflare-certs.sh
#
# Creates a combined CA bundle that includes the Cloudflare WARP root CA,
# then prints the env vars needed for common tools (Node, Python, pip, curl, git, etc.).
#
# Usage:
#   ./scripts/fix-cloudflare-certs.sh          # Create bundle + print env exports
#   ./scripts/fix-cloudflare-certs.sh --check   # Diagnose only, no changes
#   eval "$(./scripts/fix-cloudflare-certs.sh)" # Apply env vars to current shell
set -euo pipefail

CERT_DIR="$HOME/.cloudflare-certs"
COMBINED_BUNDLE="$CERT_DIR/combined-ca-bundle.pem"
SYSTEM_CERTS="/etc/ssl/cert.pem"
CF_CERT="/Library/Application Support/Cloudflare/installed_cert.pem"
CF_CERT_ALIAS="Gateway CA - Cloudflare Managed G1"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

check_only=false
if [[ "${1:-}" == "--check" ]]; then
  check_only=true
fi

# --- Diagnosis ---

echo "=== Cloudflare WARP TLS Certificate Diagnosis ===" >&2

# 1. Check if WARP is running
if pgrep -q "Cloudflare WARP" 2>/dev/null || pgrep -q "warp-svc" 2>/dev/null; then
  echo -e "${GREEN}[OK]${NC} Cloudflare WARP is running" >&2
else
  echo -e "${YELLOW}[WARN]${NC} Cloudflare WARP does not appear to be running" >&2
fi

# 2. Check if Cloudflare cert is in system keychain
if security find-certificate -c "Cloudflare" /Library/Keychains/System.keychain &>/dev/null; then
  echo -e "${GREEN}[OK]${NC} Cloudflare root CA found in system keychain" >&2
else
  echo -e "${RED}[FAIL]${NC} Cloudflare root CA NOT found in system keychain" >&2
  echo "  → Ask your IT admin to install the Cloudflare WARP root CA" >&2
  exit 1
fi

# 3. Check for the installed cert file
if [[ -f "$CF_CERT" ]]; then
  echo -e "${GREEN}[OK]${NC} Cloudflare cert file exists at: $CF_CERT" >&2
else
  echo -e "${YELLOW}[WARN]${NC} Cloudflare cert file not found at: $CF_CERT" >&2
  echo "  → Extracting from system keychain instead..." >&2
fi

# 4. Check system cert bundle
if [[ -f "$SYSTEM_CERTS" ]]; then
  echo -e "${GREEN}[OK]${NC} System CA bundle exists at: $SYSTEM_CERTS" >&2
else
  echo -e "${RED}[FAIL]${NC} System CA bundle not found at: $SYSTEM_CERTS" >&2
  exit 1
fi

# 5. Check current env vars
echo "" >&2
echo "=== Current Environment ===" >&2
for var in NODE_EXTRA_CA_CERTS SSL_CERT_FILE REQUESTS_CA_BUNDLE PIP_CERT CURL_CA_BUNDLE GIT_SSL_CAINFO; do
  val="${!var:-}"
  if [[ -n "$val" ]]; then
    echo -e "  ${GREEN}$var${NC}=$val" >&2
  else
    echo -e "  ${YELLOW}$var${NC}=(not set)" >&2
  fi
done

if $check_only; then
  echo "" >&2
  echo "=== Check complete. Run without --check to create the combined bundle. ===" >&2
  exit 0
fi

# --- Build combined CA bundle ---

echo "" >&2
echo "=== Building Combined CA Bundle ===" >&2

mkdir -p "$CERT_DIR"

# Get the Cloudflare cert (prefer installed file, fall back to keychain extraction)
cf_cert_content=""
if [[ -f "$CF_CERT" ]]; then
  cf_cert_content=$(cat "$CF_CERT")
else
  cf_cert_content=$(security find-certificate -a -c "Cloudflare" -p /Library/Keychains/System.keychain 2>/dev/null)
fi

if [[ -z "$cf_cert_content" ]]; then
  echo -e "${RED}[FAIL]${NC} Could not extract Cloudflare certificate" >&2
  exit 1
fi

# Combine: system certs + Cloudflare cert
{
  cat "$SYSTEM_CERTS"
  echo ""
  echo "# Cloudflare WARP Gateway CA"
  echo "$cf_cert_content"
} > "$COMBINED_BUNDLE"

echo -e "${GREEN}[OK]${NC} Combined CA bundle created at: $COMBINED_BUNDLE" >&2

# Also copy the standalone Cloudflare cert for tools that support "extra" certs
standalone="$CERT_DIR/cloudflare-warp-ca.pem"
echo "$cf_cert_content" > "$standalone"
echo -e "${GREEN}[OK]${NC} Standalone Cloudflare cert at: $standalone" >&2

# --- Print env exports ---
# These go to stdout so they can be eval'd or appended to a shell profile

echo "" >&2
echo "=== Environment Variables ===" >&2
echo "Add these to your shell profile (~/.zshrc, ~/.bashrc, etc.):" >&2
echo "" >&2

cat <<EXPORTS
# Cloudflare WARP TLS certificate configuration
# Generated by fix-cloudflare-certs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
export NODE_EXTRA_CA_CERTS="$standalone"
export SSL_CERT_FILE="$COMBINED_BUNDLE"
export REQUESTS_CA_BUNDLE="$COMBINED_BUNDLE"
export PIP_CERT="$COMBINED_BUNDLE"
export CURL_CA_BUNDLE="$COMBINED_BUNDLE"
export GIT_SSL_CAINFO="$COMBINED_BUNDLE"
export CARGO_HTTP_CAINFO="$COMBINED_BUNDLE"
export DENO_CERT="$standalone"
EXPORTS

echo "" >&2
echo -e "${GREEN}Done.${NC} To apply now: eval \"\$(./scripts/fix-cloudflare-certs.sh)\"" >&2
echo "To make permanent: append the exports above to your ~/.zshrc" >&2
