[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
lib_deps =
    arduino-libraries/Servo@^1.2.2
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
